export const AppPermissions = {
  VIEW_ASSETS: 'VIEW_ASSETS',
  CREATE_ASSET: 'CREATE_ASSET',
  UPDATE_ASSET: 'UPDATE_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',

  CREATE_REQUEST: 'CREATE_REQUEST',
  VIEW_REQUESTS: 'VIEW_REQUESTS',
  UPDATE_REQUEST: 'UPDATE_REQUEST',

  APPROVE_REQUEST: 'APPROVE_REQUEST',
  REJECT_REQUEST: 'REJECT_REQUEST',

  ASSIGN_ASSET: 'ASSIGN_ASSET',
  RETURN_ASSET: 'RETURN_ASSET',
  TRANSFER_ASSET: 'TRANSFER_ASSET',

  MANAGE_MAINTENANCE: 'MANAGE_MAINTENANCE',
  MANAGE_CATEGORIES: 'MANAGE_CATEGORIES',
  MANAGE_LOCATIONS: 'MANAGE_LOCATIONS',
} as const;

export type AppPermission = (typeof AppPermissions)[keyof typeof AppPermissions];
